# Generated by Django 2.2.19 on 2021-04-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_look_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='look',
            name='is_video',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
